execution:
  # Needs websockets for subscriptions
  api: ws://localhost:8545
  settings:
    # The duration after the last received block at which to start giving warnings (3 levels),
    # each a higher level of severity.
    # Valid time units: "ns", "us" (or "µs"), "ms", "s", "m", "h"
    # Examples of formats: 30s, 1m12s, 600s, 2h45m
    block_time_levels:
      - 30s
      - 1m
      - 2m
    stats:
      interval: 30s
      topics:
        - p2p
beacon:
  api: http://localhost:5052
  settings:
    # Valid time units: "ns", "us" (or "µs"), "ms", "s", "m", "h"
    # Examples of formats: 30s, 1m12s, 600s, 2h45m
    block_time_levels:
      - 30s
      - 1m
      - 2m
    stats: 
      interval: 30s
      topics:
        - p2p
validator:
  api: 
  settings:
    stats:
      interval: 1m
      topics:
        - validator_uptime

# Stats configuration. These are all the possible stats to subscribe to.
stats: 
  - id: p2p
    # Enable latency checks. This will send out SYN packets to connected peers
    # to measure latency.
    latency: true